export default function B6() {
  return (
    <div className="overflow-y-auto w-2/4 h-52">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia possimus modi vero voluptatibus dignissimos officia sit porro in cupiditate! Magni reiciendis magnam, molestias aliquid eos temporibus odio hic velit repudiandae?
        Ab dolorem nesciunt modi eius asperiores repellat distinctio pariatur doloremque ipsa beatae temporibus eveniet voluptatibus ratione aut, ducimus est eligendi, animi rerum sint itaque labore! Eveniet delectus maxime voluptas quod?
        Accusamus, deleniti voluptatibus rerum soluta id adipisci fugiat quos veritatis alias laborum optio vero eos cupiditate aliquam, porro nisi dolor officiis odit laudantium obcaecati labore harum! Voluptas fuga debitis sapiente.
        Deserunt fugiat, ea quos, praesentium rerum itaque rem atque quisquam modi cupiditate nulla vitae molestias nostrum asperiores iste a. Exercitationem eligendi autem unde reprehenderit inventore fugiat, accusamus excepturi odit corporis.
        Error sequi ullam voluptatibus debitis deleniti provident, quod sapiente sed enim, quo blanditiis itaque. Labore molestias beatae distinctio commodi velit eius, repudiandae voluptatem maxime facilis nesciunt. Et minima rerum delectus.
        Libero distinctio eius dolorum, exercitationem nulla delectus magnam quia vel sunt autem modi ipsa ipsum aliquid, a pariatur eaque velit laudantium aut itaque tenetur quasi. Autem nobis itaque earum soluta?
        Reprehenderit libero sit sed velit at, officia sint provident, ducimus tenetur quis quae quia iure minima omnis laborum ipsam, assumenda aperiam accusamus architecto ipsa asperiores repudiandae vero incidunt. Suscipit, similique.
        Veniam voluptates, iure beatae enim unde repellat temporibus voluptate velit! Aliquam nihil molestias tempora nobis minima sunt excepturi animi quos soluta itaque. Corporis reiciendis corrupti harum totam consequuntur perferendis dolore.
        Ratione, eius? Ipsum, odit itaque ipsa molestiae eligendi explicabo praesentium dignissimos quaerat, soluta ad ut a quos quo. Maxime nostrum ab at neque vitae. Velit nostrum officia nam suscipit neque?
        Magni voluptatibus distinctio alias at repellat laborum ab dolorum quae ex molestias, sequi, quod optio illo! Incidunt, ullam architecto atque laboriosam vero veritatis aspernatur provident, adipisci non rerum, voluptate cupiditate!
        Consequuntur expedita obcaecati iste, facilis accusantium nihil, sapiente nisi quasi tempora quas corrupti voluptas perspiciatis excepturi illo adipisci distinctio consequatur aspernatur est vitae similique, dolorem rerum ratione magnam odit. Dicta.
        Optio ab fuga soluta vero. Eum accusamus sit possimus vitae, asperiores quaerat. Voluptates sit pariatur officiis deleniti consequuntur necessitatibus veritatis temporibus porro tempora perspiciatis, unde magnam dolorum asperiores maxime deserunt!
        Doloremque consectetur a accusamus unde! Id totam expedita optio asperiores tempore praesentium amet aliquam ipsum quod vitae aspernatur architecto nesciunt, iste aperiam ipsam? Explicabo autem dolor provident eveniet voluptates cum.
        Quidem aspernatur tempore facilis sint alias ratione architecto, inventore fugiat velit animi repellendus quia! Blanditiis, iure sequi exercitationem quibusdam ad porro voluptas alias non aliquam aspernatur voluptatibus quis itaque facere.
        Vitae harum provident veritatis aliquam praesentium animi quibusdam neque. Harum nesciunt dolorem et atque nam voluptas, temporibus quas sunt libero non est quasi? Eligendi magni sit, nemo dignissimos maxime dolores.
        Consequatur quod, commodi iusto officiis modi dolor et dolorem rerum quas ipsam, incidunt eum fugit delectus laboriosam hic odit minus quibusdam voluptates, sit reiciendis deleniti excepturi explicabo? Aspernatur, aliquam quibusdam!
        Saepe ad dolor maiores voluptate, culpa accusantium alias repudiandae nisi praesentium consequatur, perferendis possimus. Nostrum quaerat tempore eum dolore dolores consequatur rerum aliquam. Vel reiciendis quasi tenetur a. Accusantium, rem!
        Sapiente quod neque fuga sint dicta natus magnam consequuntur similique quos, mollitia recusandae quibusdam non alias adipisci cupiditate, necessitatibus eos tempore quisquam modi tempora voluptatum ad ullam beatae pariatur? Repellendus.
        Voluptatibus eligendi omnis, nostrum eveniet fuga obcaecati commodi, officia exercitationem veritatis sequi nesciunt pariatur, sunt ab blanditiis. Quasi, veritatis obcaecati officia, eius amet quos dolore ducimus, doloribus id alias at!
        Tenetur, qui accusamus atque nobis impedit quidem perferendis nam doloribus? Velit repudiandae, magni voluptas enim unde sint rem cumque provident? Qui nemo, expedita earum magnam doloremque cum soluta dicta. Quisquam.
        Minus cum, modi enim necessitatibus culpa veritatis, quas architecto reiciendis pariatur commodi nemo a dolore soluta ea natus harum quia asperiores rerum nostrum molestias. Dolores quaerat aut perferendis id sed?
        Non impedit fuga illo maxime cumque distinctio odit fugit iure cum similique ipsam quas ex error autem eum saepe eligendi exercitationem illum pariatur deserunt, eius id necessitatibus reprehenderit dolores? Odit.
        Beatae provident enim cumque aut ducimus omnis excepturi magni quas ad mollitia. Aut, nam quia quidem temporibus, ut ea harum distinctio, sequi dolor natus sunt quisquam. Quos officia id deserunt.
        Voluptates quod earum quisquam quaerat itaque optio, exercitationem eaque laboriosam harum repellendus placeat voluptatum illum accusantium! Eveniet officiis quidem earum soluta ullam, vero doloremque, excepturi unde quibusdam hic cupiditate illo?
        Necessitatibus, illo sit officiis iste doloribus perferendis reiciendis. Vitae odit ad quis, debitis eius asperiores provident sint, quibusdam architecto ut amet quidem nostrum harum nemo nulla, maxime perferendis obcaecati officiis.
        Quod impedit aspernatur architecto quidem dignissimos corrupti necessitatibus adipisci possimus magnam, rem, cupiditate ex harum consequuntur incidunt blanditiis pariatur molestias repudiandae sed et. Qui quidem unde eligendi! Sint, maxime repudiandae.
        Ea odio cumque in culpa voluptate natus, voluptatum error esse nisi, ex temporibus facere perspiciatis aut quo nostrum autem provident voluptatibus aperiam totam accusantium quas. Hic, asperiores harum! Sapiente, obcaecati!
        Soluta sunt, maxime accusamus blanditiis similique eum rerum? Eos reiciendis ipsum numquam quo placeat eaque debitis est praesentium cum sequi in nesciunt tempora, officia, quaerat, provident architecto aliquid explicabo officiis.
        Cupiditate id doloremque autem optio, ab magni? Provident soluta in labore ipsam, inventore quam praesentium molestias placeat ex fugit tempora sunt libero deleniti accusamus ad iusto, magnam rerum eveniet iure!
        Natus earum, iure, saepe ducimus id veniam molestiae officiis architecto assumenda dolores velit accusantium blanditiis esse vel magnam quaerat nam obcaecati dicta ab aliquam at facilis consectetur suscipit corrupti! Ratione!
        Laudantium odit, distinctio nulla ratione deleniti error blanditiis autem voluptatum fugit aliquam modi consequatur ipsum excepturi nemo sit voluptas ut dolorum hic omnis sequi reiciendis aut enim fuga. Excepturi, magni!
        Cum facere vel corrupti mollitia blanditiis eveniet a! Vitae, repellendus placeat veniam voluptatum harum officiis itaque rerum commodi culpa corporis natus minima eveniet accusantium excepturi similique explicabo magni asperiores libero?
        Ipsam atque ex ducimus qui vel, eum delectus eaque accusantium dolores nesciunt iste consequuntur provident dignissimos mollitia enim sequi soluta ea reprehenderit eveniet labore voluptates odio maiores exercitationem! Quam, vel?
        Dolores sunt eum praesentium blanditiis voluptates tenetur libero quae voluptas, molestiae modi autem distinctio animi quos hic nihil? Aliquid voluptatibus, atque nihil eveniet ullam voluptate libero dolorum expedita in rerum.
        Reiciendis, quaerat aliquid consectetur cupiditate perspiciatis debitis nobis eaque recusandae a odit autem eius consequatur tempora accusantium nihil delectus sed quasi animi amet. Quis, mollitia. Accusamus sunt aut modi aperiam!
        Distinctio, pariatur hic fugit excepturi illo recusandae commodi dolorem quibusdam ab praesentium nemo et. Consequuntur rem, accusantium nesciunt, debitis atque mollitia quod hic optio in dolore quae, autem quibusdam distinctio.
        Veritatis temporibus iusto quod dolorem veniam accusantium, officiis minus aspernatur quos consequatur sed porro tempora ullam eius deserunt sit eos inventore odit deleniti voluptas! Accusantium non voluptatem aliquid temporibus aut.
        Sit esse tempora eius voluptates maxime eligendi ipsam, aspernatur possimus, aliquid incidunt iste illum dolor, quos labore similique sapiente totam cupiditate inventore velit ex nisi accusantium ratione in? Dicta, voluptas.
        Incidunt dolores ullam quam ipsa tempore expedita? Aperiam nemo deleniti, aut quibusdam, veniam minima dicta provident eius repellat porro facere officiis sint voluptates. Pariatur ullam ratione vitae possimus, voluptatem nam!
        Ullam voluptates laborum eos harum placeat perferendis quibusdam, libero tempora voluptatem dolores id odio mollitia expedita impedit veritatis illo dolor aspernatur nobis vel sit. Alias vel perferendis doloribus repellendus eligendi?
        Obcaecati, sed? Nemo, ipsa facere. Officia quis fugit sunt veniam nostrum hic facere doloremque autem quam obcaecati eveniet, harum provident mollitia corrupti facilis odit accusamus, expedita cumque inventore odio ab.
        Saepe quod voluptatem quibusdam quis libero unde nemo temporibus quisquam atque iure quidem tempore earum fugit, dicta eveniet magni dolorem! Ullam autem temporibus sint. Sed beatae deleniti amet temporibus quam?
        Cupiditate vero optio voluptatibus fugit! Consectetur non adipisci ab aut, eaque ullam asperiores laudantium animi consequuntur quas, cupiditate, dolor dolorum omnis. Laudantium, sit perferendis! Aliquid tenetur iure fugit vero quis.
        Architecto quaerat maxime voluptatibus eligendi exercitationem pariatur corrupti, dignissimos ex optio, animi quos sint repudiandae aspernatur cum numquam accusantium unde voluptatem vel provident iure voluptas excepturi. Voluptatibus hic nobis explicabo.
        Autem optio natus libero facilis in expedita error sunt neque explicabo qui recusandae reiciendis tempora molestias maxime, totam deserunt mollitia, ducimus quasi consequatur velit unde ad atque incidunt? Similique, cumque!
        Totam asperiores aspernatur ipsum doloremque, culpa accusantium ipsa molestiae suscipit tempore officia iste omnis laudantium possimus est aliquam quasi, architecto debitis eaque amet provident. Amet delectus quaerat voluptatibus nihil molestiae?
        Fugit rem dolorem odio excepturi at doloremque voluptatum et quos consequatur quae cumque veritatis officiis ex tempora tempore quo, dolor ab dicta! Laborum aut id temporibus blanditiis dolorum earum esse?
        Temporibus vel facilis ipsam est autem nulla nisi maiores ea voluptatem cumque aut sint ipsa cupiditate commodi nemo, ipsum harum quos asperiores pariatur voluptas a hic assumenda illum provident. Animi.
        Autem eveniet recusandae temporibus maxime eius. Accusamus ratione et provident aperiam distinctio culpa. In omnis corporis obcaecati earum labore quibusdam, natus quidem voluptatem libero aut quis velit officia quod dolores!
        Assumenda obcaecati odit, officia accusantium perspiciatis ratione harum dicta laboriosam dignissimos illo voluptates laborum aut minus consectetur excepturi velit quo omnis saepe esse ea temporibus in reiciendis molestias dolore! Dolores?
    </div>
  )
}
